version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: voting_db
    environment:
      POSTGRES_USER: khaleel
      POSTGRES_PASSWORD: abdulkhaleel@2004
      POSTGRES_DB: voting_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: